services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable@sha256:d4fbec16196d5c8bedf32647f0ca7165f654d92a2e81f35a373508d3226cb867"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      # Mount the integration code into the container
      - ./custom_components/indygo_pool:/config/custom_components/indygo_pool
    ports:
      - "8123:8123"
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
