services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable@sha256:8edcb16cff8158e87a3a2b48b3bcca05c30dcea0212eb6a2fe940b6d52ed216a"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      # Mount the integration code into the container
      - ./custom_components/indygo_pool:/config/custom_components/indygo_pool
    ports:
      - "8123:8123"
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
